---
- name: "create backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "inarchive backend file"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "installing node dependencies"
  shell: |
    cd ~/backend-app
    npm i
- name: "Execute node app"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: execute node

- name: print message
  debug:
    msg: "{{execute_node.stdout_lines"

- name: "configure pm2 as a service"
  become: true
  shell: |
    env   PATH=$PATH:/usr/local/bin pm2 startup systemd -u -ubuntu --hp /home/ubuntu